dist: trusty
language: ruby
sudo: false
rvm:
  - 2.4.0
  - 2.3.3
  - 2.2.6
  - jruby-9.0.5.0
gemfile:
  - gemfiles/ar50.gemfile
matrix:
  allow_failures:
    - rvm: jruby-9.0.5.0
addons:
  apt:
    packages:
      - language-pack-ko
      - mysql-server-5.6
      - mysql-client-core-5.6
      - mysql-client-5.6

before_install:
  - mysql -u root -e 'CREATE DATABASE IF NOT EXISTS mysql2rgeo_adapter_test;'
script: bundle exec rake test