language: ruby
sudo: false
rvm:
  - 2.4.0
  - 2.3.3
  - 2.2.6
  - jruby-9.0.5.0
gemfile:
  - gemfiles/ar50.gemfile
matrix:
  allow_failures:
    - rvm: jruby-9.0.5.0
addons:
  mysql: "5.6"
before_script:
  - echo "create database mysql2rgeo_adapter_test" | mysql -u mysql
script: bundle exec rake test